---
abstract: unknown
author:
  - unknown
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112150'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Rex
no_index:
  directory:
    - t
    - inc
requires:
  DBI: 0
  Digest::HMAC_SHA1: 0
  Expect: 0
  HTTP::Date: 0
  JSON::XS: 0
  LWP::Simple: 0
  LWP::UserAgent: 0
  MIME::Base64: 0
  Net::SSH2: 0.33
  Storable: 0
  XML::Simple: 0
  YAML: 0
resources:
  repository: https://github.com/krimdomu/Rex
version: v0.40.0
