--- #YAML:1.0
name:               Rex
version:            0.19.0
abstract:           ~
author:  []
license:            GPL
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    DBI:                0
    Digest::HMAC_SHA1:  0
    Expect:             0
    HTTP::Date:         0
    JSON::XS:           0
    LWP::UserAgent:     0
    MIME::Base64:       0
    Net::SSH2:          >0.33
    XML::Simple:        0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
