---
abstract: 'Remote Execution'
author:
  - 'Jan Gehring <jfried@rexify.org>'
build_requires:
  File::Temp: '0'
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.020, CPAN::Meta::Converter version 2.142060'
license: apache
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Rex
requires:
  Carp: '0'
  Cwd: '0'
  Data::Dumper: '0'
  Digest::MD5: '0'
  Exporter: '0'
  Fcntl: '0'
  File::Basename: '0'
  File::Spec: '0'
  File::Spec::Unix: '0'
  FindBin: '0'
  HTTP::Request: '0'
  HTTP::Request::Common: '0'
  IO::File: '0'
  IO::Socket: '0'
  IPC::Open3: '0'
  JSON::XS: '0'
  LWP::UserAgent: '0'
  List::MoreUtils: '0'
  List::Util: '0'
  MIME::Base64: '0'
  Net::SSH2: '0'
  POSIX: '0'
  Storable: '0'
  Symbol: '0'
  Test::Builder::Module: '0'
  Time::HiRes: '0'
  UNIVERSAL: '0'
  URI: '0'
  URI::QueryParam: '0'
  XML::Simple: '0'
  YAML: '0'
  attributes: '0'
  base: '0'
  constant: '0'
  overload: '0'
  perl: '5.008'
  strict: '0'
  vars: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/RexOps/Rex/issues
  homepage: http://www.rexify.org
  repository: https://github.com/RexOps/Rex.git
version: 0.56.1
